# Generated by Django 2.2 on 2020-07-01 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Calle', models.CharField(max_length=50)),
                ('Numero', models.IntegerField()),
                ('Ciudad', models.CharField(max_length=50)),
                ('Comuna', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.CharField(max_length=50)),
                ('Descuento', models.IntegerField()),
                ('MontoFinal', models.IntegerField()),
                ('Detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.Detalle')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('RUT', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=50)),
                ('Web', models.CharField(max_length=50)),
                ('Direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Precio', models.IntegerField()),
                ('Stock', models.IntegerField()),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.Categoria')),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.Proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='detalle',
            name='Producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.Producto'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('RUT', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=50)),
                ('Direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.Direccion')),
                ('Venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.Venta')),
            ],
        ),
    ]
